# test_name: "Benchmark" # the series of tests being run in thesis
test_name: "RunPP" # the series of tests being run in thesis
# test_name: "FastTests" # the series of tests being run in thesis
# test_name: "SlowTests" # the series of tests being run in thesis

# architecture: "E2e"
# architecture: "Serial"
# architecture: "Mod"
architecture: "PP"


n: 1
set_n: 1

n_train_steps: 50000
# n_test_laps: 2
n_test_laps: 10

# n_obstacles: 8
racing: True
# racing: False

# map_name: "columbia_small"
map_name: "f1_aut"

runs:
  - n_obstacles: 0
  - n_obstacles: 1
  - n_obstacles: 2
  - n_obstacles: 3
  - n_obstacles: 4
  - n_obstacles: 5
  - n_obstacles: 6
  - n_obstacles: 7
  - n_obstacles: 8


  # - map_name: "f1_aut"
  # - map_name: "f1_mco"
  # - map_name: "f1_esp"
  # - map_name: "f1_gbr"
  # - map_name: "columbia_small"



