# test_name: "Benchmark" # the series of tests being run in thesis
test_name: "RunPP" # the series of tests being run in thesis
# test_name: "FastTests" # the series of tests being run in thesis
# test_name: "SlowTests" # the series of tests being run in thesis

# architecture: "E2e"
# architecture: "Serial"
# architecture: "Mod"
architecture: "PP"


n: 1
set_n: 1

n_train_steps: 50000
# n_test_laps: 2
n_test_laps: 10

n_obstacles: 2
racing: True
# racing: False


runs:
  - map_name: "f1_aut"
  # - map_name: "f1_mco"
  # - map_name: "f1_esp"
  # - map_name: "f1_gbr"
  # - map_name: "columbia_small"



